# Generated by Django 4.0.6 on 2022-07-28 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0002_alter_event_booked_seats_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(5)]))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
